name: Scheduler

on:
  schedule:
    - cron: '41 16 * * 6'
    - cron: '45 16 * * 6'
    - cron: '50 16 * * 6'
    - cron: '0 17 * * 6' # Runs every Saturday 5 PM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Run the script
      env:
        URL: ${{ secrets.URL }}
        USERNAMES_PASSWORDS: ${{ secrets.USERNAMES_PASSWORDS }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        python reservation.py
